### ISSUE TITLE
License for QuadTree project

### ISSUE THREAD

**Issue by 12people** [Carla-de-Beer/processing-projects#3]
Could you please add a license to the QuadTree subproject? I'd very much like to make use of it in my own (GPL-licensed) Processing project.

The original QuadTree project that it's based on was just licensed under the MIT license: https://github.com/CodingTrain/QuadTree

**Comment by Carla-de-Beer** [comment]
Sure. No problem. I should have done this from the start, thinking about it. Thank you for reminding me. I added the MIT license to the repo as a whole. Let me know if there are any issues with these. Glad the project can be of use to someone.

**Comment by 12people** [comment]
Awesome, thank you so much!
